### ISSUE TITLE
Question about simd_abi::max_fixed_size

### ISSUE THREAD

**Issue by akrivx** [VcDevel/std-simd#45]
Hi,

I'm struggling to understand the purpose of `simd_abi::max_fixed_size`.

For example, on a [Broadwell processor](https://en.wikipedia.org/wiki/Broadwell_(microarchitecture)) where `native_simd<double>::size()` is `4`, `simd_abi::max_fixed_size<double>` is `32`.

Why isn't it `64` or `128`? In other words, what limits `simd_abi::max_fixed_size<double>` in this case?

Thanks,
Christos

**Comment by mattkretz** [comment]
The purpose allowing an implementation to document that it doesn't care about unreasonable implementation complexity and thus letting everyone pay in compile time (at least). And at the same time it's a hint to users that large widths are probably not a good idea.

In this implementation 32 is a helpful restriction for keeping the bitmask of `fixed_size_simd` in a single 32-bit register. 64 would certainly also be a reasonable choice (because most users will be on 64-bit systems). But one purpose of choosing 32 for this implementation was to learn whether it inhibits reasonable use cases. Because the TS documents 32 as the minimum an implementation has to support. For C++26 the plan is to require at least 64.

Regarding your example, why do you want a `fixed_size_simd<double, 32>` on a Broadwell processor? That's 8 registers and only useful in very few corner cases - to my knowledge.

**Comment by akrivx** [comment]
That makes perfect sense, thanks.

My case involves a program running on an HPC system with Broadwell processors.

The program focuses on HPC C++ features like standard parallel algorithms and `std::simd`. It involves many arithmetic operations on arrays of 32 doubles, including operations like `x=y*z` or `x=y*z+w`, where `x,y,z,w` are arrays of 32 doubles.

The compilers I work with already vectorise such operations when using `std::for_each_n(std::execution::unseq, ...)` with `std::views::iota(0, 32).begin()` to implement them.

`fixed_size_simd<double, 32>` is more elegant as it results in compact and easy-to-read code and performs similarly (or slightly better for some reason).

However, I wasn't sure whether that was an abuse of `fixed_size_simd`.

**Comment by mattkretz** [comment]
Interesting data points. Thanks. Yes, for the specific problem you're looking at, unrolling the loop to work on 8 registers independently saves the loop overhead - specifically the conditional jump at the end of the loop.
In general, the intent for `simd<T>` is to use it for larger loops than that. But occasionally the input data set is small. In that case, what you're doing is totally reasonable. I've used a single `simd<char>` to parse a small number into a `short` (super-fast `atoi`, basically) before.
For a value-type of `char` the restriction to 32 - and even 64 - is a bit on the low side. My new C++26 implementation will likely support up to 64 and then more only steps of `simd<T>::size()`. In that case `max_fixed_size` will say 64 but more is possible.

**Comment by mattkretz** [comment]
I close this issue, but feel free to continue the discussion.

**Comment by akrivx** [comment]
Thanks for the detailed answer.
